config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, :email, :password
  validates :terms_of_services, acceptance: true
  validates :password, confirmation: {case_sensitive: true},
                       length: {in: 5..15}
  validates :password_confirmation, presence: true
  # validates :name, exclusion: { in: %w(_ @ - $),
  #   message: "%{value} is not a valid, no special character" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new  
  end

  def create
    @user = User.new(user_params)
 
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy

  	redirect_to users_path  	
  end

  private
  def user_params
  	params.require(:user).permit(:name, :password, :password_confirmation, :email, :terms_of_services)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>REGISTERED</h1>

<%= link_to 'New user', new_user_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user_path(user) %></td> 
      <td><%= link_to 'destroy', user_path(user),
      				method: :delete,
      				data: {confirm:'Are you sure to deleter?'}%></td>     
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<%= form_for @user do |f| %> 
 
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %> 
    <p style="color:red;font-size: 15px"><%= @user.errors.full_messages_for(:name).first %></p> 
  </div>
 
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
    <p style="color:red;font-size: 15px"><%= @user.errors.full_messages_for(:password).first %></p>
  </div>

  <div>
    <%= f.label :"Confirmation Password" %><br>
    <%= f.password_field :password_confirmation %>
    <p style="color:red;font-size: 15px"><%= @user.errors.full_messages_for(:password_confirmation).first %></p>
  </div>

  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
    <p style="color:red;font-size: 15px"><%= @user.errors.full_messages_for(:email).first %></p>
  </div>

  <div>    
    <span><%= f.check_box :terms_of_services %></span>
    <span><%= f.label :terms_of_services %></span>
  </div>
  <div>
    <p style="color:red;font-size: 15px"><%= @user.errors.full_messages_for(:terms_of_services).first %> </p>
  </div>
 
  <div>
    <%= f.submit "Register" %>
  </div>
 
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
 
<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>
  
<%= link_to 'Back', users_path %>